spring:
  application:
    name: starttap
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quill-db}
    username: ${SPRING_DATASOURCE_USERNAME:isa}
    password: ${SPRING_DATASOURCE_PASSWORD:isaisa}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  level:
    root: debug


  mail:
    host: smtp.gmail.com
    port: 587
    username: isaqurbanov112@gmail.com
    # Use an App Password, NOT your regular account password
    password: nfpnpsuncpcfkjim
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        # Recommended: Set timeouts to avoid blocking threads
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


dreamSecretKey2006: ${SALT_KEY:test-secret-key}
jwt:
  expiration: 900000
  refresh-expiration: 604800000


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:test-cloud}
  api-key: ${CLOUDINARY_API_KEY:test-key}
  api-secret: ${CLOUDINARY_API_SECRET:test-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

  metrics:
    tags:
      application: starttap-backend
      instance: ${HOSTNAME}


app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}



