spring:
  application:
    name: quill

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


dreamSecretKey2006: ${SALT_KEY}

jwt:
  expiration: 900000
  refresh-expiration: 604800000