spring.application.name=quill

spring.datasource.url=jdbc:postgresql://dpg-d6hvaudm5p6s73brfdag-a.oregon-postgres.render.com:5432/quill_db_zkpm?sslmode=require
spring.datasource.username=isa
spring.datasource.password=kZarnPkmWL1AaqNbDOgQ3srBWVRaxfwE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
